vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /upload/user_avatar
            upload_destination: '%kernel.project_dir%/public/upload/user_avatar'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer