index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_login'
        permanent: false
        keepQueryParams: false
        keepRequestMethod: false
