---
- name: Installation application
  hosts: all
  remote_user: "{{ remote_admin_user }}"
  tasks:
      - include_vars:
          dir: roles/server_user/vars/
      - include_vars:
          file: vars.yaml
      - include_role:
          name: ansistrano.deploy
