---
- name: Installation du serveur
  hosts: all
  remote_user: "{{ remote_admin_user }}"
  become: true
  vars_files:
      - vars.yaml
  tasks:
  - include_role:
      name: tools
  - include_role:
      name: php_sury
  - include_role:
      name: apache
  - include_role:
      name: fpm_composer
  - include_role:
      name: mysql_server
  - include_role:
      name: yarn
  - include_role:
      name: log_rotation
  - include_role:
      name: backup

  ## Répertoires de l'application
  - name: Lao | Répertoire
    ansible.builtin.file:
        path: "{{ application_path }}"
        state: directory
        owner: "{{ remote_admin_user }}"
          
  ## Répertoires à conserver entre les releases
  - name: Lao | Répertoires ansistrano shared
    ansible.builtin.file:
        path: "{{ ansistrano_deploy_to }}/shared/lao/public/upload"
        state: directory
        owner: "{{ fpm_user }}"


  - name: Lao | Composants supplémentaires
    apt:
        update_cache: yes
        name:
            - php-mysql
            - php-intl
            - php-gd
        state: present
          
  - name: Lao | Composant pour développement
    apt:
        update_cache: yes
        name:
            - chromium-driver
            #- TODO geckodriver
        state: present
    when: symfony_env != 'prod'